/**
 * Complete list of world countries for the signup form.
 * Labels are in French (canonical value stored in profiles.country),
 * with an English alias used for search.
 */

export interface Country {
  flag: string;
  label: string;
  en: string;
  code: string;
}

export const COUNTRIES: Country[] = [
  { flag: "🇨🇩", label: "RD Congo", en: "Democratic Republic of the Congo", code: "+243" },
  { flag: "🇦🇫", label: "Afghanistan", en: "Afghanistan", code: "+93" },
  { flag: "🇿🇦", label: "Afrique du Sud", en: "South Africa", code: "+27" },
  { flag: "🇦🇱", label: "Albanie", en: "Albania", code: "+355" },
  { flag: "🇩🇿", label: "Algérie", en: "Algeria", code: "+213" },
  { flag: "🇩🇪", label: "Allemagne", en: "Germany", code: "+49" },
  { flag: "🇦🇩", label: "Andorre", en: "Andorra", code: "+376" },
  { flag: "🇦🇴", label: "Angola", en: "Angola", code: "+244" },
  { flag: "🇦🇬", label: "Antigua-et-Barbuda", en: "Antigua and Barbuda", code: "+1268" },
  { flag: "🇸🇦", label: "Arabie saoudite", en: "Saudi Arabia", code: "+966" },
  { flag: "🇦🇷", label: "Argentine", en: "Argentina", code: "+54" },
  { flag: "🇦🇲", label: "Arménie", en: "Armenia", code: "+374" },
  { flag: "🇦🇺", label: "Australie", en: "Australia", code: "+61" },
  { flag: "🇦🇹", label: "Autriche", en: "Austria", code: "+43" },
  { flag: "🇦🇿", label: "Azerbaïdjan", en: "Azerbaijan", code: "+994" },
  { flag: "🇧🇸", label: "Bahamas", en: "Bahamas", code: "+1242" },
  { flag: "🇧🇭", label: "Bahreïn", en: "Bahrain", code: "+973" },
  { flag: "🇧🇩", label: "Bangladesh", en: "Bangladesh", code: "+880" },
  { flag: "🇧🇧", label: "Barbade", en: "Barbados", code: "+1246" },
  { flag: "🇧🇾", label: "Biélorussie", en: "Belarus", code: "+375" },
  { flag: "🇧🇪", label: "Belgique", en: "Belgium", code: "+32" },
  { flag: "🇧🇿", label: "Belize", en: "Belize", code: "+501" },
  { flag: "🇧🇯", label: "Bénin", en: "Benin", code: "+229" },
  { flag: "🇧🇹", label: "Bhoutan", en: "Bhutan", code: "+975" },
  { flag: "🇧🇴", label: "Bolivie", en: "Bolivia", code: "+591" },
  { flag: "🇧🇦", label: "Bosnie-Herzégovine", en: "Bosnia and Herzegovina", code: "+387" },
  { flag: "🇧🇼", label: "Botswana", en: "Botswana", code: "+267" },
  { flag: "🇧🇷", label: "Brésil", en: "Brazil", code: "+55" },
  { flag: "🇧🇳", label: "Brunei", en: "Brunei", code: "+673" },
  { flag: "🇧🇬", label: "Bulgarie", en: "Bulgaria", code: "+359" },
  { flag: "🇧🇫", label: "Burkina Faso", en: "Burkina Faso", code: "+226" },
  { flag: "🇧🇮", label: "Burundi", en: "Burundi", code: "+257" },
  { flag: "🇰🇭", label: "Cambodge", en: "Cambodia", code: "+855" },
  { flag: "🇨🇲", label: "Cameroun", en: "Cameroon", code: "+237" },
  { flag: "🇨🇦", label: "Canada", en: "Canada", code: "+1" },
  { flag: "🇨🇻", label: "Cap-Vert", en: "Cape Verde", code: "+238" },
  { flag: "🇨🇱", label: "Chili", en: "Chile", code: "+56" },
  { flag: "🇨🇳", label: "Chine", en: "China", code: "+86" },
  { flag: "🇨🇾", label: "Chypre", en: "Cyprus", code: "+357" },
  { flag: "🇨🇴", label: "Colombie", en: "Colombia", code: "+57" },
  { flag: "🇰🇲", label: "Comores", en: "Comoros", code: "+269" },
  { flag: "🇨🇬", label: "Congo", en: "Republic of the Congo", code: "+242" },
  { flag: "🇰🇵", label: "Corée du Nord", en: "North Korea", code: "+850" },
  { flag: "🇰🇷", label: "Corée du Sud", en: "South Korea", code: "+82" },
  { flag: "🇨🇷", label: "Costa Rica", en: "Costa Rica", code: "+506" },
  { flag: "🇨🇮", label: "Côte d'Ivoire", en: "Ivory Coast", code: "+225" },
  { flag: "🇭🇷", label: "Croatie", en: "Croatia", code: "+385" },
  { flag: "🇨🇺", label: "Cuba", en: "Cuba", code: "+53" },
  { flag: "🇩🇰", label: "Danemark", en: "Denmark", code: "+45" },
  { flag: "🇩🇯", label: "Djibouti", en: "Djibouti", code: "+253" },
  { flag: "🇩🇲", label: "Dominique", en: "Dominica", code: "+1767" },
  { flag: "🇪🇬", label: "Égypte", en: "Egypt", code: "+20" },
  { flag: "🇦🇪", label: "Émirats arabes unis", en: "United Arab Emirates", code: "+971" },
  { flag: "🇪🇨", label: "Équateur", en: "Ecuador", code: "+593" },
  { flag: "🇪🇷", label: "Érythrée", en: "Eritrea", code: "+291" },
  { flag: "🇪🇸", label: "Espagne", en: "Spain", code: "+34" },
  { flag: "🇪🇪", label: "Estonie", en: "Estonia", code: "+372" },
  { flag: "🇸🇿", label: "Eswatini", en: "Eswatini", code: "+268" },
  { flag: "🇺🇸", label: "États-Unis", en: "United States", code: "+1" },
  { flag: "🇪🇹", label: "Éthiopie", en: "Ethiopia", code: "+251" },
  { flag: "🇫🇯", label: "Fidji", en: "Fiji", code: "+679" },
  { flag: "🇫🇮", label: "Finlande", en: "Finland", code: "+358" },
  { flag: "🇫🇷", label: "France", en: "France", code: "+33" },
  { flag: "🇬🇦", label: "Gabon", en: "Gabon", code: "+241" },
  { flag: "🇬🇲", label: "Gambie", en: "Gambia", code: "+220" },
  { flag: "🇬🇪", label: "Géorgie", en: "Georgia", code: "+995" },
  { flag: "🇬🇭", label: "Ghana", en: "Ghana", code: "+233" },
  { flag: "🇬🇷", label: "Grèce", en: "Greece", code: "+30" },
  { flag: "🇬🇩", label: "Grenade", en: "Grenada", code: "+1473" },
  { flag: "🇬🇹", label: "Guatemala", en: "Guatemala", code: "+502" },
  { flag: "🇬🇳", label: "Guinée", en: "Guinea", code: "+224" },
  { flag: "🇬🇼", label: "Guinée-Bissau", en: "Guinea-Bissau", code: "+245" },
  { flag: "🇬🇶", label: "Guinée équatoriale", en: "Equatorial Guinea", code: "+240" },
  { flag: "🇬🇾", label: "Guyana", en: "Guyana", code: "+592" },
  { flag: "🇭🇹", label: "Haïti", en: "Haiti", code: "+509" },
  { flag: "🇭🇳", label: "Honduras", en: "Honduras", code: "+504" },
  { flag: "🇭🇺", label: "Hongrie", en: "Hungary", code: "+36" },
  { flag: "🇮🇳", label: "Inde", en: "India", code: "+91" },
  { flag: "🇮🇩", label: "Indonésie", en: "Indonesia", code: "+62" },
  { flag: "🇮🇶", label: "Irak", en: "Iraq", code: "+964" },
  { flag: "🇮🇷", label: "Iran", en: "Iran", code: "+98" },
  { flag: "🇮🇪", label: "Irlande", en: "Ireland", code: "+353" },
  { flag: "🇮🇸", label: "Islande", en: "Iceland", code: "+354" },
  { flag: "🇮🇱", label: "Israël", en: "Israel", code: "+972" },
  { flag: "🇮🇹", label: "Italie", en: "Italy", code: "+39" },
  { flag: "🇯🇲", label: "Jamaïque", en: "Jamaica", code: "+1876" },
  { flag: "🇯🇵", label: "Japon", en: "Japan", code: "+81" },
  { flag: "🇯🇴", label: "Jordanie", en: "Jordan", code: "+962" },
  { flag: "🇰🇿", label: "Kazakhstan", en: "Kazakhstan", code: "+7" },
  { flag: "🇰🇪", label: "Kenya", en: "Kenya", code: "+254" },
  { flag: "🇰🇬", label: "Kirghizistan", en: "Kyrgyzstan", code: "+996" },
  { flag: "🇰🇮", label: "Kiribati", en: "Kiribati", code: "+686" },
  { flag: "🇽🇰", label: "Kosovo", en: "Kosovo", code: "+383" },
  { flag: "🇰🇼", label: "Koweït", en: "Kuwait", code: "+965" },
  { flag: "🇱🇦", label: "Laos", en: "Laos", code: "+856" },
  { flag: "🇱🇸", label: "Lesotho", en: "Lesotho", code: "+266" },
  { flag: "🇱🇻", label: "Lettonie", en: "Latvia", code: "+371" },
  { flag: "🇱🇧", label: "Liban", en: "Lebanon", code: "+961" },
  { flag: "🇱🇷", label: "Libéria", en: "Liberia", code: "+231" },
  { flag: "🇱🇾", label: "Libye", en: "Libya", code: "+218" },
  { flag: "🇱🇮", label: "Liechtenstein", en: "Liechtenstein", code: "+423" },
  { flag: "🇱🇹", label: "Lituanie", en: "Lithuania", code: "+370" },
  { flag: "🇱🇺", label: "Luxembourg", en: "Luxembourg", code: "+352" },
  { flag: "🇲🇰", label: "Macédoine du Nord", en: "North Macedonia", code: "+389" },
  { flag: "🇲🇬", label: "Madagascar", en: "Madagascar", code: "+261" },
  { flag: "🇲🇾", label: "Malaisie", en: "Malaysia", code: "+60" },
  { flag: "🇲🇼", label: "Malawi", en: "Malawi", code: "+265" },
  { flag: "🇲🇻", label: "Maldives", en: "Maldives", code: "+960" },
  { flag: "🇲🇱", label: "Mali", en: "Mali", code: "+223" },
  { flag: "🇲🇹", label: "Malte", en: "Malta", code: "+356" },
  { flag: "🇲🇦", label: "Maroc", en: "Morocco", code: "+212" },
  { flag: "🇲🇭", label: "Îles Marshall", en: "Marshall Islands", code: "+692" },
  { flag: "🇲🇺", label: "Maurice", en: "Mauritius", code: "+230" },
  { flag: "🇲🇷", label: "Mauritanie", en: "Mauritania", code: "+222" },
  { flag: "🇲🇽", label: "Mexique", en: "Mexico", code: "+52" },
  { flag: "🇫🇲", label: "Micronésie", en: "Micronesia", code: "+691" },
  { flag: "🇲🇩", label: "Moldavie", en: "Moldova", code: "+373" },
  { flag: "🇲🇨", label: "Monaco", en: "Monaco", code: "+377" },
  { flag: "🇲🇳", label: "Mongolie", en: "Mongolia", code: "+976" },
  { flag: "🇲🇪", label: "Monténégro", en: "Montenegro", code: "+382" },
  { flag: "🇲🇿", label: "Mozambique", en: "Mozambique", code: "+258" },
  { flag: "🇲🇲", label: "Myanmar", en: "Myanmar", code: "+95" },
  { flag: "🇳🇦", label: "Namibie", en: "Namibia", code: "+264" },
  { flag: "🇳🇷", label: "Nauru", en: "Nauru", code: "+674" },
  { flag: "🇳🇵", label: "Népal", en: "Nepal", code: "+977" },
  { flag: "🇳🇮", label: "Nicaragua", en: "Nicaragua", code: "+505" },
  { flag: "🇳🇪", label: "Niger", en: "Niger", code: "+227" },
  { flag: "🇳🇬", label: "Nigeria", en: "Nigeria", code: "+234" },
  { flag: "🇳🇴", label: "Norvège", en: "Norway", code: "+47" },
  { flag: "🇳🇿", label: "Nouvelle-Zélande", en: "New Zealand", code: "+64" },
  { flag: "🇴🇲", label: "Oman", en: "Oman", code: "+968" },
  { flag: "🇺🇬", label: "Ouganda", en: "Uganda", code: "+256" },
  { flag: "🇺🇿", label: "Ouzbékistan", en: "Uzbekistan", code: "+998" },
  { flag: "🇵🇰", label: "Pakistan", en: "Pakistan", code: "+92" },
  { flag: "🇵🇼", label: "Palaos", en: "Palau", code: "+680" },
  { flag: "🇵🇸", label: "Palestine", en: "Palestine", code: "+970" },
  { flag: "🇵🇦", label: "Panama", en: "Panama", code: "+507" },
  { flag: "🇵🇬", label: "Papouasie-Nouvelle-Guinée", en: "Papua New Guinea", code: "+675" },
  { flag: "🇵🇾", label: "Paraguay", en: "Paraguay", code: "+595" },
  { flag: "🇳🇱", label: "Pays-Bas", en: "Netherlands", code: "+31" },
  { flag: "🇵🇪", label: "Pérou", en: "Peru", code: "+51" },
  { flag: "🇵🇭", label: "Philippines", en: "Philippines", code: "+63" },
  { flag: "🇵🇱", label: "Pologne", en: "Poland", code: "+48" },
  { flag: "🇵🇹", label: "Portugal", en: "Portugal", code: "+351" },
  { flag: "🇶🇦", label: "Qatar", en: "Qatar", code: "+974" },
  { flag: "🇷🇴", label: "Roumanie", en: "Romania", code: "+40" },
  { flag: "🇬🇧", label: "Royaume-Uni", en: "United Kingdom", code: "+44" },
  { flag: "🇷🇺", label: "Russie", en: "Russia", code: "+7" },
  { flag: "🇷🇼", label: "Rwanda", en: "Rwanda", code: "+250" },
  { flag: "🇰🇳", label: "Saint-Kitts-et-Nevis", en: "Saint Kitts and Nevis", code: "+1869" },
  { flag: "🇱🇨", label: "Sainte-Lucie", en: "Saint Lucia", code: "+1758" },
  { flag: "🇻🇨", label: "Saint-Vincent-et-les-Grenadines", en: "Saint Vincent and the Grenadines", code: "+1784" },
  { flag: "🇼🇸", label: "Samoa", en: "Samoa", code: "+685" },
  { flag: "🇸🇲", label: "Saint-Marin", en: "San Marino", code: "+378" },
  { flag: "🇸🇹", label: "Sao Tomé-et-Principe", en: "Sao Tome and Principe", code: "+239" },
  { flag: "🇸🇳", label: "Sénégal", en: "Senegal", code: "+221" },
  { flag: "🇷🇸", label: "Serbie", en: "Serbia", code: "+381" },
  { flag: "🇸🇨", label: "Seychelles", en: "Seychelles", code: "+248" },
  { flag: "🇸🇱", label: "Sierra Leone", en: "Sierra Leone", code: "+232" },
  { flag: "🇸🇬", label: "Singapour", en: "Singapore", code: "+65" },
  { flag: "🇸🇰", label: "Slovaquie", en: "Slovakia", code: "+421" },
  { flag: "🇸🇮", label: "Slovénie", en: "Slovenia", code: "+386" },
  { flag: "🇸🇴", label: "Somalie", en: "Somalia", code: "+252" },
  { flag: "🇸🇩", label: "Soudan", en: "Sudan", code: "+249" },
  { flag: "🇸🇸", label: "Soudan du Sud", en: "South Sudan", code: "+211" },
  { flag: "🇱🇰", label: "Sri Lanka", en: "Sri Lanka", code: "+94" },
  { flag: "🇸🇪", label: "Suède", en: "Sweden", code: "+46" },
  { flag: "🇨🇭", label: "Suisse", en: "Switzerland", code: "+41" },
  { flag: "🇸🇷", label: "Suriname", en: "Suriname", code: "+597" },
  { flag: "🇸🇾", label: "Syrie", en: "Syria", code: "+963" },
  { flag: "🇹🇯", label: "Tadjikistan", en: "Tajikistan", code: "+992" },
  { flag: "🇹🇿", label: "Tanzanie", en: "Tanzania", code: "+255" },
  { flag: "🇹🇩", label: "Tchad", en: "Chad", code: "+235" },
  { flag: "🇨🇿", label: "Tchéquie", en: "Czech Republic", code: "+420" },
  { flag: "🇹🇭", label: "Thaïlande", en: "Thailand", code: "+66" },
  { flag: "🇹🇱", label: "Timor oriental", en: "Timor-Leste", code: "+670" },
  { flag: "🇹🇬", label: "Togo", en: "Togo", code: "+228" },
  { flag: "🇹🇴", label: "Tonga", en: "Tonga", code: "+676" },
  { flag: "🇹🇹", label: "Trinité-et-Tobago", en: "Trinidad and Tobago", code: "+1868" },
  { flag: "🇹🇳", label: "Tunisie", en: "Tunisia", code: "+216" },
  { flag: "🇹🇲", label: "Turkménistan", en: "Turkmenistan", code: "+993" },
  { flag: "🇹🇷", label: "Turquie", en: "Turkey", code: "+90" },
  { flag: "🇹🇻", label: "Tuvalu", en: "Tuvalu", code: "+688" },
  { flag: "🇺🇦", label: "Ukraine", en: "Ukraine", code: "+380" },
  { flag: "🇺🇾", label: "Uruguay", en: "Uruguay", code: "+598" },
  { flag: "🇻🇺", label: "Vanuatu", en: "Vanuatu", code: "+678" },
  { flag: "🇻🇦", label: "Vatican", en: "Vatican City", code: "+379" },
  { flag: "🇻🇪", label: "Venezuela", en: "Venezuela", code: "+58" },
  { flag: "🇻🇳", label: "Viêt Nam", en: "Vietnam", code: "+84" },
  { flag: "🇾🇪", label: "Yémen", en: "Yemen", code: "+967" },
  { flag: "🇿🇲", label: "Zambie", en: "Zambia", code: "+260" },
  { flag: "🇿🇼", label: "Zimbabwe", en: "Zimbabwe", code: "+263" },
  { flag: "🇨🇫", label: "Centrafrique", en: "Central African Republic", code: "+236" },
  { flag: "🇩🇴", label: "République dominicaine", en: "Dominican Republic", code: "+1809" },
  { flag: "🇸🇻", label: "Salvador", en: "El Salvador", code: "+503" },
  { flag: "🇸🇧", label: "Îles Salomon", en: "Solomon Islands", code: "+677" },
];

/** Search countries by French label or English alias (accent-insensitive). */
export function searchCountries(query: string): Country[] {
  const q = query
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
  if (!q) return COUNTRIES;
  return COUNTRIES.filter(
    (c) =>
      c.label.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().includes(q) ||
      c.en.toLowerCase().includes(q),
  );
}
