// @ts-nocheck
import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { getGuardDiscussion, reactToGuardContent, replyToGuardDiscussion, reportGuardContent, toggleGuardFollow } from "@/lib/salle-de-garde.functions";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Bell, Eye, Flag, Heart, Lightbulb, Lock, MessageCircle, ThumbsUp } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/salle-de-garde/discussion/$id")({ component: GuardDiscussion });

function GuardDiscussion() {
  const { id } = Route.useParams(); const qc = useQueryClient(); const get = useServerFn(getGuardDiscussion); const reply = useServerFn(replyToGuardDiscussion); const follow = useServerFn(toggleGuardFollow); const react = useServerFn(reactToGuardContent); const report = useServerFn(reportGuardContent);
  const { data, isLoading } = useQuery({ queryKey: ["guard-discussion", id], queryFn: () => get({ data: { id } }) });
  const [content, setContent] = useState(""); const [replyTo, setReplyTo] = useState<string | null>(null);
  const refresh = () => qc.invalidateQueries({ queryKey: ["guard-discussion", id] });
  const replyMut = useMutation({ mutationFn: () => reply({ data: { discussion_id: id, content, parent_reply_id: replyTo } }), onSuccess: () => { setContent(""); setReplyTo(null); refresh(); }, onError: (e) => toast.error(e instanceof Error && e.message.includes("LOCKED") ? "Cette discussion est fermée." : "Réponse impossible pour le moment.") });
  const followMut = useMutation({ mutationFn: () => follow({ data: { discussion_id: id } }), onSuccess: refresh });
  const reactionMut = useMutation({ mutationFn: (type: "useful" | "relevant" | "interesting") => react({ data: { discussion_id: id, type } }), onSuccess: refresh });
  const reportMut = useMutation({ mutationFn: () => report({ data: { discussion_id: id, reason: "misinformation" } }), onSuccess: () => toast.success("Signalement transmis à la modération."), onError: () => toast.error("Signalement impossible") });
  if (isLoading || !data) return <div className="py-16 text-center text-muted-foreground">Chargement de la discussion…</div>;
  const { discussion, replies, reactions } = data;
  const reactionCount = (type: string) => reactions.filter((r) => r.type === type).length;
  return <div className="mx-auto max-w-4xl space-y-5"><Link to="/salle-de-garde/$specialty" params={{ specialty: discussion.specialty_id }} className="text-sm text-primary hover:underline">← Retour à la spécialité</Link>
    <article className="rounded-3xl border bg-card p-6 shadow-[var(--shadow-card)] md:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Salle de garde</p><Button variant="ghost" size="sm" onClick={() => reportMut.mutate()}><Flag className="mr-1 h-4 w-4" />Signaler</Button></div><h1 className="mt-3 font-serif text-3xl md:text-4xl">{discussion.title}</h1><p className="mt-4 text-sm text-muted-foreground">{discussion.author?.name} — {discussion.author?.profession} · {new Date(discussion.created_at).toLocaleString("fr-FR")}</p><div className="mt-6 whitespace-pre-wrap leading-7 text-foreground/90">{discussion.content}</div><div className="mt-6 flex flex-wrap gap-2 border-t pt-5"><Button variant="outline" size="sm" onClick={() => reactionMut.mutate("useful")}><ThumbsUp className="mr-1 h-4 w-4" />Utile {reactionCount("useful") || ""}</Button><Button variant="outline" size="sm" onClick={() => reactionMut.mutate("relevant")}><Lightbulb className="mr-1 h-4 w-4" />Pertinent {reactionCount("relevant") || ""}</Button><Button variant="outline" size="sm" onClick={() => reactionMut.mutate("interesting")}><Heart className="mr-1 h-4 w-4" />Intéressant {reactionCount("interesting") || ""}</Button><Button variant="outline" size="sm" className="ml-auto" onClick={() => followMut.mutate()}><Bell className="mr-1 h-4 w-4" />{data.following ? "Ne plus suivre" : "Suivre cette discussion"}</Button></div><p className="mt-4 text-xs text-muted-foreground"><Eye className="mr-1 inline h-3.5 w-3.5" />{discussion.views_count} vues</p></article>
    <section className="rounded-3xl border bg-card p-6 shadow-[var(--shadow-soft)]"><h2 className="flex items-center gap-2 font-serif text-2xl"><MessageCircle className="h-5 w-5 text-primary" />Discussion ({replies.length})</h2>{discussion.is_locked && <p className="mt-4 rounded-xl border border-warning/30 bg-warning/10 p-3 text-sm">🔒 Cette discussion est fermée. Les nouvelles réponses ne sont plus autorisées.</p>}<div className="mt-5 space-y-4">{replies.map((r) => <article key={r.id} className={`rounded-2xl border bg-secondary/30 p-4 ${r.parent_reply_id ? "ml-4 sm:ml-10" : ""}`}><p className="text-sm font-semibold">{r.author?.name} <span className="font-normal text-muted-foreground">— {r.author?.profession}</span></p><p className="mt-1 text-xs text-muted-foreground">{new Date(r.created_at).toLocaleString("fr-FR")}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{r.content}</p>{!discussion.is_locked && <Button variant="ghost" size="sm" className="mt-2" onClick={() => setReplyTo(r.id)}>Répondre</Button>}</article>)}</div>{!discussion.is_locked && <form className="mt-6 border-t pt-5" onSubmit={(e) => { e.preventDefault(); if (content.trim()) replyMut.mutate(); }}><p className="mb-2 text-sm font-medium">{replyTo ? "Réponse à un membre" : "Votre réponse"}</p><Textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder="Partagez un raisonnement clinique constructif…" rows={5} disabled={replyMut.isPending} required minLength={2} />{replyTo && <Button type="button" variant="ghost" size="sm" className="mt-2" onClick={() => setReplyTo(null)}>Annuler la réponse directe</Button>}<Button type="submit" className="mt-3" disabled={replyMut.isPending || !content.trim()}>{replyMut.isPending ? "Publication…" : "Publier ma réponse"}</Button></form>}</section>
  </div>;
}
