/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedJuryRouteImport } from './routes/_authenticated/jury'
import { Route as AuthenticatedJuryHistoryRouteImport } from './routes/_authenticated/jury-history'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSalleDeGardeRouteImport } from './routes/_authenticated/salle-de-garde'
import { Route as AuthenticatedSpecialtiesRouteImport } from './routes/_authenticated/specialties'
import { Route as LegalDocumentRouteImport } from './routes/legal.$document'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminDiversityRouteImport } from './routes/_authenticated/admin.diversity'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedConsultationIdRouteImport } from './routes/_authenticated/consultation.$id'
import { Route as AuthenticatedReportIdRouteImport } from './routes/_authenticated/report.$id'
import { Route as AuthenticatedSalleDeGardeSpecialtyRouteImport } from './routes/_authenticated/salle-de-garde.$specialty'
import { Route as AuthenticatedSubspecialtiesSpecialtyRouteImport } from './routes/_authenticated/subspecialties.$specialty'
import { Route as AuthenticatedSalleDeGardeDiscussionIdRouteImport } from './routes/_authenticated/salle-de-garde.discussion.$id'
import { Route as ApiPublicHooksJuryTickRouteImport } from './routes/api/public/hooks/jury-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJuryRoute = AuthenticatedJuryRouteImport.update({
  id: '/jury',
  path: '/jury',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJuryHistoryRoute =
  AuthenticatedJuryHistoryRouteImport.update({
    id: '/jury-history',
    path: '/jury-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalleDeGardeRoute =
  AuthenticatedSalleDeGardeRouteImport.update({
    id: '/salle-de-garde',
    path: '/salle-de-garde',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpecialtiesRoute =
  AuthenticatedSpecialtiesRouteImport.update({
    id: '/specialties',
    path: '/specialties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LegalDocumentRoute = LegalDocumentRouteImport.update({
  id: '/legal/$document',
  path: '/legal/$document',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDiversityRoute =
  AuthenticatedAdminDiversityRouteImport.update({
    id: '/diversity',
    path: '/diversity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedConsultationIdRoute =
  AuthenticatedConsultationIdRouteImport.update({
    id: '/consultation/$id',
    path: '/consultation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportIdRoute = AuthenticatedReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalleDeGardeSpecialtyRoute =
  AuthenticatedSalleDeGardeSpecialtyRouteImport.update({
    id: '/$specialty',
    path: '/$specialty',
    getParentRoute: () => AuthenticatedSalleDeGardeRoute,
  } as any)
const AuthenticatedSubspecialtiesSpecialtyRoute =
  AuthenticatedSubspecialtiesSpecialtyRouteImport.update({
    id: '/subspecialties/$specialty',
    path: '/subspecialties/$specialty',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalleDeGardeDiscussionIdRoute =
  AuthenticatedSalleDeGardeDiscussionIdRouteImport.update({
    id: '/discussion/$id',
    path: '/discussion/$id',
    getParentRoute: () => AuthenticatedSalleDeGardeRoute,
  } as any)
const ApiPublicHooksJuryTickRoute = ApiPublicHooksJuryTickRouteImport.update({
  id: '/api/public/hooks/jury-tick',
  path: '/api/public/hooks/jury-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/jury': typeof AuthenticatedJuryRoute
  '/jury-history': typeof AuthenticatedJuryHistoryRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/salle-de-garde': typeof AuthenticatedSalleDeGardeRouteWithChildren
  '/specialties': typeof AuthenticatedSpecialtiesRoute
  '/legal/$document': typeof LegalDocumentRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/diversity': typeof AuthenticatedAdminDiversityRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/consultation/$id': typeof AuthenticatedConsultationIdRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/salle-de-garde/$specialty': typeof AuthenticatedSalleDeGardeSpecialtyRoute
  '/subspecialties/$specialty': typeof AuthenticatedSubspecialtiesSpecialtyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/salle-de-garde/discussion/$id': typeof AuthenticatedSalleDeGardeDiscussionIdRoute
  '/api/public/hooks/jury-tick': typeof ApiPublicHooksJuryTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/jury': typeof AuthenticatedJuryRoute
  '/jury-history': typeof AuthenticatedJuryHistoryRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/salle-de-garde': typeof AuthenticatedSalleDeGardeRouteWithChildren
  '/specialties': typeof AuthenticatedSpecialtiesRoute
  '/legal/$document': typeof LegalDocumentRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/diversity': typeof AuthenticatedAdminDiversityRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/consultation/$id': typeof AuthenticatedConsultationIdRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/salle-de-garde/$specialty': typeof AuthenticatedSalleDeGardeSpecialtyRoute
  '/subspecialties/$specialty': typeof AuthenticatedSubspecialtiesSpecialtyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/salle-de-garde/discussion/$id': typeof AuthenticatedSalleDeGardeDiscussionIdRoute
  '/api/public/hooks/jury-tick': typeof ApiPublicHooksJuryTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/jury': typeof AuthenticatedJuryRoute
  '/_authenticated/jury-history': typeof AuthenticatedJuryHistoryRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/salle-de-garde': typeof AuthenticatedSalleDeGardeRouteWithChildren
  '/_authenticated/specialties': typeof AuthenticatedSpecialtiesRoute
  '/legal/$document': typeof LegalDocumentRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/diversity': typeof AuthenticatedAdminDiversityRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/consultation/$id': typeof AuthenticatedConsultationIdRoute
  '/_authenticated/report/$id': typeof AuthenticatedReportIdRoute
  '/_authenticated/salle-de-garde/$specialty': typeof AuthenticatedSalleDeGardeSpecialtyRoute
  '/_authenticated/subspecialties/$specialty': typeof AuthenticatedSubspecialtiesSpecialtyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/salle-de-garde/discussion/$id': typeof AuthenticatedSalleDeGardeDiscussionIdRoute
  '/api/public/hooks/jury-tick': typeof ApiPublicHooksJuryTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/history'
    | '/home'
    | '/jury'
    | '/jury-history'
    | '/premium'
    | '/profile'
    | '/salle-de-garde'
    | '/specialties'
    | '/legal/$document'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/diversity'
    | '/admin/users'
    | '/consultation/$id'
    | '/report/$id'
    | '/salle-de-garde/$specialty'
    | '/subspecialties/$specialty'
    | '/admin/'
    | '/salle-de-garde/discussion/$id'
    | '/api/public/hooks/jury-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/history'
    | '/home'
    | '/jury'
    | '/jury-history'
    | '/premium'
    | '/profile'
    | '/salle-de-garde'
    | '/specialties'
    | '/legal/$document'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/diversity'
    | '/admin/users'
    | '/consultation/$id'
    | '/report/$id'
    | '/salle-de-garde/$specialty'
    | '/subspecialties/$specialty'
    | '/admin'
    | '/salle-de-garde/discussion/$id'
    | '/api/public/hooks/jury-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/jury'
    | '/_authenticated/jury-history'
    | '/_authenticated/premium'
    | '/_authenticated/profile'
    | '/_authenticated/salle-de-garde'
    | '/_authenticated/specialties'
    | '/legal/$document'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/diversity'
    | '/_authenticated/admin/users'
    | '/_authenticated/consultation/$id'
    | '/_authenticated/report/$id'
    | '/_authenticated/salle-de-garde/$specialty'
    | '/_authenticated/subspecialties/$specialty'
    | '/_authenticated/admin/'
    | '/_authenticated/salle-de-garde/discussion/$id'
    | '/api/public/hooks/jury-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  LegalDocumentRoute: typeof LegalDocumentRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksJuryTickRoute: typeof ApiPublicHooksJuryTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jury': {
      id: '/_authenticated/jury'
      path: '/jury'
      fullPath: '/jury'
      preLoaderRoute: typeof AuthenticatedJuryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jury-history': {
      id: '/_authenticated/jury-history'
      path: '/jury-history'
      fullPath: '/jury-history'
      preLoaderRoute: typeof AuthenticatedJuryHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salle-de-garde': {
      id: '/_authenticated/salle-de-garde'
      path: '/salle-de-garde'
      fullPath: '/salle-de-garde'
      preLoaderRoute: typeof AuthenticatedSalleDeGardeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/specialties': {
      id: '/_authenticated/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof AuthenticatedSpecialtiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legal/$document': {
      id: '/legal/$document'
      path: '/legal/$document'
      fullPath: '/legal/$document'
      preLoaderRoute: typeof LegalDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diversity': {
      id: '/_authenticated/admin/diversity'
      path: '/diversity'
      fullPath: '/admin/diversity'
      preLoaderRoute: typeof AuthenticatedAdminDiversityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/consultation/$id': {
      id: '/_authenticated/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/consultation/$id'
      preLoaderRoute: typeof AuthenticatedConsultationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$id': {
      id: '/_authenticated/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof AuthenticatedReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salle-de-garde/$specialty': {
      id: '/_authenticated/salle-de-garde/$specialty'
      path: '/$specialty'
      fullPath: '/salle-de-garde/$specialty'
      preLoaderRoute: typeof AuthenticatedSalleDeGardeSpecialtyRouteImport
      parentRoute: typeof AuthenticatedSalleDeGardeRoute
    }
    '/_authenticated/subspecialties/$specialty': {
      id: '/_authenticated/subspecialties/$specialty'
      path: '/subspecialties/$specialty'
      fullPath: '/subspecialties/$specialty'
      preLoaderRoute: typeof AuthenticatedSubspecialtiesSpecialtyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salle-de-garde/discussion/$id': {
      id: '/_authenticated/salle-de-garde/discussion/$id'
      path: '/discussion/$id'
      fullPath: '/salle-de-garde/discussion/$id'
      preLoaderRoute: typeof AuthenticatedSalleDeGardeDiscussionIdRouteImport
      parentRoute: typeof AuthenticatedSalleDeGardeRoute
    }
    '/api/public/hooks/jury-tick': {
      id: '/api/public/hooks/jury-tick'
      path: '/api/public/hooks/jury-tick'
      fullPath: '/api/public/hooks/jury-tick'
      preLoaderRoute: typeof ApiPublicHooksJuryTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDiversityRoute: typeof AuthenticatedAdminDiversityRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDiversityRoute: AuthenticatedAdminDiversityRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSalleDeGardeRouteChildren {
  AuthenticatedSalleDeGardeSpecialtyRoute: typeof AuthenticatedSalleDeGardeSpecialtyRoute
  AuthenticatedSalleDeGardeDiscussionIdRoute: typeof AuthenticatedSalleDeGardeDiscussionIdRoute
}

const AuthenticatedSalleDeGardeRouteChildren: AuthenticatedSalleDeGardeRouteChildren =
  {
    AuthenticatedSalleDeGardeSpecialtyRoute:
      AuthenticatedSalleDeGardeSpecialtyRoute,
    AuthenticatedSalleDeGardeDiscussionIdRoute:
      AuthenticatedSalleDeGardeDiscussionIdRoute,
  }

const AuthenticatedSalleDeGardeRouteWithChildren =
  AuthenticatedSalleDeGardeRoute._addFileChildren(
    AuthenticatedSalleDeGardeRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJuryRoute: typeof AuthenticatedJuryRoute
  AuthenticatedJuryHistoryRoute: typeof AuthenticatedJuryHistoryRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSalleDeGardeRoute: typeof AuthenticatedSalleDeGardeRouteWithChildren
  AuthenticatedSpecialtiesRoute: typeof AuthenticatedSpecialtiesRoute
  AuthenticatedConsultationIdRoute: typeof AuthenticatedConsultationIdRoute
  AuthenticatedReportIdRoute: typeof AuthenticatedReportIdRoute
  AuthenticatedSubspecialtiesSpecialtyRoute: typeof AuthenticatedSubspecialtiesSpecialtyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJuryRoute: AuthenticatedJuryRoute,
  AuthenticatedJuryHistoryRoute: AuthenticatedJuryHistoryRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSalleDeGardeRoute: AuthenticatedSalleDeGardeRouteWithChildren,
  AuthenticatedSpecialtiesRoute: AuthenticatedSpecialtiesRoute,
  AuthenticatedConsultationIdRoute: AuthenticatedConsultationIdRoute,
  AuthenticatedReportIdRoute: AuthenticatedReportIdRoute,
  AuthenticatedSubspecialtiesSpecialtyRoute:
    AuthenticatedSubspecialtiesSpecialtyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  LegalDocumentRoute: LegalDocumentRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksJuryTickRoute: ApiPublicHooksJuryTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
